import { defineType, defineField } from 'sanity'

export const firmType = defineType({
  name: 'firmType',
  title: 'Firm Type / Solution',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Firm Type Name', type: 'string', validation: (r) => r.required(), description: 'e.g. "Private Equity", "Venture Capital"' }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' }, validation: (r) => r.required() }),
    defineField({ name: 'eyebrow', title: 'Eyebrow', type: 'string' }),
    defineField({ name: 'h1', title: 'H1', type: 'string' }),
    defineField({ name: 'h2Hero', title: 'H2 Sub-headline', type: 'string' }),
    defineField({ name: 'h3Hero', title: 'H3 Tertiary', type: 'string' }),
    defineField({ name: 'heroBody', title: 'Hero Body', type: 'blockContent' }),
    defineField({ name: 'heroImage', title: 'Hero Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'challengeH2', title: 'Challenge Headline', type: 'string' }),
    defineField({ name: 'challengeH3', title: 'Challenge Sub-headline', type: 'string' }),
    defineField({ name: 'challengePressuresIntro', title: 'Pressures Intro', type: 'string' }),
    defineField({ name: 'challengePressures', title: 'Pressures', type: 'blockContent' }),
    defineField({ name: 'challengeFailuresIntro', title: 'Failures Intro', type: 'string' }),
    defineField({ name: 'challengeFailures', title: 'Failures', type: 'blockContent' }),
    defineField({ name: 'solutionH2', title: 'Solution Headline', type: 'string' }),
    defineField({ name: 'solutionH3', title: 'Solution Sub-headline', type: 'string' }),
    defineField({ name: 'solutionBody', title: 'Solution Body', type: 'blockContent' }),
    defineField({
      name: 'capabilities',
      title: 'Capabilities',
      type: 'array',
      of: [{ type: 'object', fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'bullets', title: 'Bullets', type: 'blockContent' },
      ] }],
      validation: (r) => r.max(4),
    }),
    defineField({ name: 'valueH2', title: 'Value Headline', type: 'string' }),
    defineField({ name: 'valueContent', title: 'Value Content', type: 'blockContent' }),
    defineField({ name: 'securityH2', title: 'Security Headline', type: 'string' }),
    defineField({ name: 'securityBullets', title: 'Security Bullets', type: 'blockContent' }),
    defineField({ name: 'complianceBullets', title: 'Compliance Bullets', type: 'blockContent' }),
    defineField({ name: 'integrationH2', title: 'Integration Headline', type: 'string' }),
    defineField({ name: 'integrationContent', title: 'Integration Content', type: 'blockContent' }),
    defineField({ name: 'resultsH2', title: 'Results Headline', type: 'string' }),
    defineField({ name: 'resultsContent', title: 'Results Content', type: 'blockContent' }),
    defineField({ name: 'implementationH2', title: 'Implementation Headline', type: 'string' }),
    defineField({
      name: 'implementationPhases',
      title: 'Implementation Phases',
      type: 'array',
      of: [{ type: 'object', fields: [
        { name: 'title', title: 'Phase Title', type: 'string' },
        { name: 'bullets', title: 'Steps', type: 'blockContent' },
      ] }],
    }),
    defineField({ name: 'differentiationH2', title: 'Differentiation Headline', type: 'string' }),
    defineField({ name: 'differentiationContent', title: 'Differentiation Content', type: 'blockContent' }),
    defineField({ name: 'ctaH2', title: 'CTA Headline', type: 'string' }),
    defineField({ name: 'ctaH3', title: 'CTA Sub-headline', type: 'string' }),
    defineField({ name: 'ctaBody', title: 'CTA Body', type: 'blockContent' }),
    defineField({ name: 'ctaButtonLabel', title: 'CTA Button Label', type: 'string' }),
    defineField({ name: 'ctaTagline', title: 'CTA Tagline', type: 'string' }),
    defineField({ name: 'ctaDemoList', title: 'Demo List', type: 'blockContent' }),
    defineField({ name: 'faqContent', title: 'FAQ Content', type: 'blockContent' }),
    defineField({ name: 'relatedCaseStudies', title: 'Related Case Studies', type: 'array', of: [{ type: 'reference', to: [{ type: 'caseStudy' }] }] }),
    defineField({ name: 'relatedUseCases', title: 'Related Use Cases', type: 'array', of: [{ type: 'reference', to: [{ type: 'useCase' }] }] }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo' }),
  ],
  preview: {
    select: { title: 'title', media: 'heroImage' },
  },
})
