import { defineType, defineField } from 'sanity'

export const icpPage = defineType({
  name: 'icpPage',
  title: 'ICP / Persona Page',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Persona Name', type: 'string', validation: (r) => r.required(), description: 'e.g. "Investment Analysts", "Portfolio Managers"' }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' }, validation: (r) => r.required() }),
    defineField({ name: 'h1', title: 'H1', type: 'string' }),
    defineField({ name: 'heroTagline', title: 'Tagline', type: 'string' }),
    defineField({ name: 'heroBody', title: 'Hero Body', type: 'blockContent' }),
    defineField({ name: 'valueH2', title: 'Value Section Headline', type: 'string' }),
    defineField({
      name: 'valuePillars',
      title: 'Value Pillars',
      type: 'array',
      of: [{ type: 'object', fields: [
        { name: 'title', title: 'Pillar Title', type: 'string' },
        { name: 'bullets', title: 'Bullets', type: 'blockContent' },
      ] }],
      validation: (r) => r.max(3),
    }),
    defineField({ name: 'capabilitiesH2', title: 'Capabilities Headline', type: 'string' }),
    defineField({ name: 'capabilitiesSubtitle', title: 'Capabilities Subtitle', type: 'string' }),
    defineField({
      name: 'capabilities',
      title: 'Capabilities',
      type: 'array',
      of: [{ type: 'object', fields: [
        { name: 'title', title: 'Title', type: 'string' },
        { name: 'content', title: 'Content', type: 'blockContent' },
      ] }],
      validation: (r) => r.max(3),
    }),
    defineField({ name: 'workflowH2', title: 'Workflow Section Headline', type: 'string' }),
    defineField({
      name: 'workflows',
      title: 'Workflow Comparisons',
      type: 'array',
      of: [{ type: 'object', fields: [
        { name: 'title', title: 'Workflow Title', type: 'string' },
        { name: 'before', title: 'Before', type: 'string' },
        { name: 'after', title: 'After', type: 'string' },
      ] }],
      validation: (r) => r.max(3),
    }),
    defineField({ name: 'metricsH2', title: 'Metrics Headline', type: 'string' }),
    defineField({ name: 'metricsContent', title: 'Metrics Content', type: 'blockContent' }),
    defineField({ name: 'securityH2', title: 'Security Headline', type: 'string' }),
    defineField({ name: 'securityContent', title: 'Security Content', type: 'blockContent' }),
    defineField({ name: 'testimonialQuote', title: 'Testimonial Quote', type: 'text' }),
    defineField({ name: 'socialContent', title: 'Social Proof Content', type: 'blockContent' }),
    defineField({ name: 'pricingContent', title: 'Pricing Content', type: 'blockContent' }),
    defineField({ name: 'purposeBuiltContent', title: 'Purpose Built Content', type: 'blockContent' }),
    defineField({ name: 'ctaH2', title: 'CTA Headline', type: 'string' }),
    defineField({ name: 'ctaSubheadline', title: 'CTA Sub-headline', type: 'string' }),
    defineField({ name: 'ctaBody', title: 'CTA Body', type: 'blockContent' }),
    defineField({ name: 'ctaButtonLabel', title: 'CTA Button Label', type: 'string' }),
    defineField({ name: 'ctaTagline', title: 'CTA Tagline', type: 'string' }),
    defineField({ name: 'relatedUseCases', title: 'Related Use Cases', type: 'array', of: [{ type: 'reference', to: [{ type: 'useCase' }] }] }),
    defineField({ name: 'relatedCaseStudies', title: 'Related Case Studies', type: 'array', of: [{ type: 'reference', to: [{ type: 'caseStudy' }] }] }),
    defineField({ name: 'relatedFeatures', title: 'Related Features', type: 'array', of: [{ type: 'reference', to: [{ type: 'platformFeature' }] }] }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo' }),
  ],
  preview: {
    select: { title: 'title' },
  },
})
