export const enterpriseQuery = `
  *[_type == "enterpriseSalesPage"][0]{
    heroHeadline, heroSubheadline,
    heroImage{ asset->{ url, metadata { lqip, dimensions } } },
    heroCtas[]{ label, url, style, openInNewTab },
    socialProofHeadline,
    socialProofLogos[]{ asset->{ url } },
    proofPointsEyebrow,
    proofPoints[]{ value, description },
    researchHeadline, researchEyebrow, researchBody,
    capabilitiesEyebrow, capabilitiesStickyTitle,
    capabilityCards[]{ title, subtitle, howHelpsLabel, howHelpsText },
    roiHeadline,
    metrics[]{ value, label, context },
    byTheNumbersHeadline,
    byTheNumbersItems[]{ label },
    securityEyebrow,
    securityCertifications[]{ title, description },
    securityFeaturesHeadline, securityFeaturesCtaLabel, securityFeaturesCtaUrl,
    securityFeatures[]{ title, description },
    whyChooseHeadline,
    whyChooseCards[]{ eyebrow, body },
    timelineHeadline,
    timelineSteps[]{ title, description },
    faqsTitle,
    faqs[]{ question, answer },
    testimonials[]{ quote, attribution, authorName },
    footerTagline, footerCtaLabel, footerCtaUrl,
    formHeadline, formDescription,
    benefits[]{ title, description, icon },
    securitySummary,
    complianceBadges[]{ label, icon{ asset->{ url } } },
    seo
  }
`
